// Reusable scene-first shell. Specific engineering content lives in each scene module.
export function sceneShell({title,goal,tabs}){
 const root=document.getElementById('sceneApp');root.innerHTML=`<div id="sceneCanvas" tabindex="0" aria-label="三维桥梁；空白处拖动旋转，车身拖动可挪车。方向键旋转相机。"></div><section class="scene-hud"><p class="kicker">从车辆位置，看懂主梁分担</p><h1>${title}</h1><p id="sceneGoal">${goal}</p><button id="mainAction" class="primary">看看下面各根梁</button><p id="sceneStatus" class="scene-status" role="status"></p></section><nav class="scene-dock" aria-label="探索工具"></nav><section class="scene-drawer" role="region" aria-label="当前工具" hidden><div class="drawer-heading"><strong id="panelTitle"></strong><button id="closePanel">收起 ×</button></div></section><div id="sceneCaption" class="scene-caption"></div><p id="sceneError" role="alert"></p>`;
 const dock=root.querySelector('.scene-dock'),drawer=root.querySelector('.scene-drawer'),panels={};let current='',invoker=null;
 for(const tab of tabs){const b=document.createElement('button');b.textContent=tab.label;b.dataset.panel=tab.id;b.setAttribute('aria-expanded','false');dock.append(b);const p=document.createElement('div');p.hidden=true;p.dataset.contents=tab.id;p.innerHTML=tab.html;drawer.append(p);panels[tab.id]=p;b.onclick=()=>current===tab.id?close():open(tab.id,b);}
 function open(id,b){current=id;invoker=b;drawer.hidden=false;Object.entries(panels).forEach(([k,p])=>p.hidden=k!==id);root.querySelector('#panelTitle').textContent=tabs.find(t=>t.id===id).title;dock.querySelectorAll('button').forEach(b=>b.setAttribute('aria-expanded',String(b.dataset.panel===id)));root.querySelector('#closePanel').focus();}
 function close(){drawer.hidden=true;current='';dock.querySelectorAll('button').forEach(b=>b.setAttribute('aria-expanded','false'));invoker?.focus();}
 root.querySelector('#closePanel').onclick=close;document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!drawer.hidden){e.stopPropagation();close();}});return{root,panels,open,close,canvas:root.querySelector('#sceneCanvas')};
}
