import {sceneShell} from './scene-shell.js';
import {distribute,deformationOf,spanShape} from './transverse-model.mjs';
import {createTransverseScene} from './transverse-scene.js';
const $=id=>document.getElementById(id),state={count:5,carX:0,total:120,edgeRatio:1},trials=[];let revealed=false,selected=2,result,deformation;
const shell=sceneShell({title:'车靠一侧开，<br>哪根梁分得更多？',goal:'这座桥下面有几根主梁？先看清，再挪车。',tabs:[
 {id:'move',label:'挪车',title:'车放在哪里？',html:'<label>横向车位（相对桥中线）<input id="offset" type="range" min="-4.3" max="4.3" step="0.1" value="0"><output id="offsetOut">0.00 m</output></label><div class="button-row"><button id="moveLeft">← 挪一点</button><button id="centerCar">回到中间</button><button id="moveRight">挪一点 →</button></div><label>整车教学荷载<select id="totalLoad"><option value="60">60 kN</option><option value="120" selected>120 kN</option><option value="180">180 kN</option></select></label><p>也可以直接拖动车身。车在桥跨中间，当前只改变横向位置。</p>'},
 {id:'bridge',label:'换几根梁',title:'下面有几根主梁？',html:'<label>主梁数量<select id="girderCount"><option>4</option><option selected>5</option><option>6</option><option>8</option></select></label><p id="bridgeSize"></p><details><summary>再改末号梁的刚度</summary><label>末号梁相对刚度<select id="edgeRatio"><option value="0.5">其余梁的 0.5 倍</option><option value="1" selected>与其余梁相同</option><option value="2">其余梁的 2 倍</option></select></label><p>这里改变等效竖向刚度，不按造型大小猜刚度；横向连接仍按刚性处理。</p></details>'},
 {id:'look',label:'看升降',title:'和原来的位置比一比',html:'<div class="button-row"><button id="frontView">跨中看升降</button><button id="underView">从桥下看</button></div><div class="button-row"><button id="topView">俯视</button><button id="isoView">回到整桥</button></div><label class="check"><input id="showDeformation" type="checkbox" checked> 显示变形，虚线保留原位</label><label>把两种变化分开看<select id="motionMode"><option value="total">合在一起：实际模型结果</option><option value="settlement">只看整体下沉</option><option value="rotation">只看偏载转动</option></select></label><p id="motionExplanation"></p><label>变形显示放大倍数<select id="deformationScale"><option value="1">1倍</option><option value="100">100倍</option><option value="250" selected>250倍</option><option value="500">500倍</option></select></label><details><summary>构造和尺寸</summary><label class="check"><input id="transparentDeck" type="checkbox"> 半透明桥面</label><label class="check"><input id="hideVehicle" type="checkbox"> 暂时隐藏车辆</label><label class="check"><input id="highlightDiaphragms" type="checkbox"> 找出三道横隔板</label><label class="check"><input id="showSpacing" type="checkbox"> 标出尺寸（未变形尺寸）</label><select id="dimensionType"><option value="width">桥宽 B 与梁距 d</option><option value="span">跨度 L 与横隔板位置</option><option value="vehicle">轮距、轴距与车位 e</option></select><p>本教学桥跨内三道横隔板距一端5、10、15 m。端部支承构件另计。B为桥面全宽，d为相邻主梁中心距，L为支承中心间的跨度。</p></details>'},
 {id:'challenge',label:'试个问题',title:'自己选一个目标',html:'<select id="challenge"><option value="equal">车放在哪，各梁分得一样多？</option><option value="edge">五根梁，让5号梁分到至少30%</option></select><p id="challengePrompt"></p><button id="checkChallenge" class="primary">核对这个位置</button><p id="challengeFeedback" role="status"></p><details><summary>给我一点提示</summary><p id="challengeHint"></p></details>'},
 {id:'trials',label:'我的方案',title:'留住结果，换个位置比较',html:'<button id="keepTrial">记下当前方案</button><p id="trialMessage" role="status"></p><ul id="trialList" class="trial-list"></ul><button id="exportTrials">导出方案和各梁分担</button>'},
 {id:'notes',label:'说明与代码',title:'需要时再查',html:'<p><strong>当前模型：刚性横向连接 + 各主梁等效竖向刚度。</strong>横向分担由位移协调与平衡求解，纵向变形用等效跨中力的简支梁解析形状展示，不是整座桥的空间有限元计算。</p><p>表中的 ηᵢ=Rᵢ/P，是这一模型下单辆车的荷载分担比例。它不是可直接套入所有截面、内力和规范荷载组合的设计横向分布系数 m。</p><details><summary>它怎样算？</summary><p>连接处共同下沉和转动：Rᵢ=kᵢ(a+b yᵢ)。再用合力 ΣRᵢ=P 和合矩 ΣRᵢyᵢ=P e 求 a、b。相同刚度时化为 Rᵢ=P/n+P e yᵢ/Σyⱼ²。再按等效主梁刚度 K₀=48EI/L³ 换算位移 wᵢ=Rᵢ/(K₀kᵢ)。默认 EI=3.4×10⁶ kN·m²、L=20 m，K₀=20400 kN/m。位移向下为正，图形按固定倍数放大。</p><pre id="modelCode"></pre></details><details><summary>整体下沉与转动，围绕哪里？</summary><p>刚度中心 yₖ=Σkᵢyᵢ/Σkᵢ，先下沉 uₖ=P/ΣKᵢ，再叠加转动 θ(y−yₖ)。这一中心也会下沉，并非固定支点。合成位移为零的位置 y₀=−u₀/θ，才是图上“不升不降的位置”；它可能在桥外，此时桥内仍可全部下沉。仅看转动分量时出现的上移，不等于合成位移已经上移。</p></details><details><summary>变形模型与教学参数</summary><p>将各梁分担 Rᵢ 等效为作用在其跨中的集中力，按简支梁解析形状展示纵向弯曲。E=34 GPa、I=0.100 m⁴、EI=3.4×10⁶ kN·m²是明示的教学设置，I不由当前简化造型反算；末号梁相对刚度同时缩放其EI。真实四轮沿桥长的位置、桥面板局部弯曲和有限横隔刚度尚未纳入此模型。</p><p>变形图 X=X₀+放大倍数×U；原位虚线与尺寸保持未变形基准。整车造型随两排车轮处的桥面倾斜，不计算车辆悬架动力。场景展示静力状态变化，不表示桥梁自由振动或车速效应。</p></details><details><summary>横隔板与负值怎么理解？</summary><p>带孔横隔板表示各主梁之间的横向联系。当前把横向联系理想化为刚性，不计算孔洞附近应力，也不以切换显示来改变连接刚度。</p><p>正 R 表示主梁承接向下的荷载；负 R 表示该梁与横向体系之间需要反向传力。若实际支承只能承压并发生脱空，必须换接触模型，不能把负值截成零后沿用其余结果。</p></details><details><summary>尺寸和车辆来源</summary><p>教学桥跨度L=20 m、桥面全宽B=10.80 m，两侧各悬出0.60 m。板厚t=0.22 m、主梁造型底距桥面顶1.44 m；这些构造尺寸不代替截面验算。外侧主梁中心距9.60 m不变；五梁时等间距2.40 m，取自教材梁桥章的板带算例间距，其他梁数按固定桥宽重排。构件外形未经过实桥设计验算。</p><p>车辆：Kenney Car Kit 3.1（CC0），统一放大1.8倍；轮距1.62 m、轴距2.916 m。四轮等载，默认整车120 kN，均为教学设置，不代表规范车辆。</p><a href="assets/kenney-car/README.md">资产来源与改动</a></details><p><a href="../chapters/ch03.html" target="_blank">查阅教材梁桥章</a> · <a href="core-learning.html?unit=C04U05&view=full" target="_blank">用二维模型再看一次</a></p>'}
]});
const sceneView=createTransverseScene({host:shell.canvas,onMove:move,onSelect:i=>{selected=i;updateDisplay();}});
const board=document.createElement('section');board.className='share-board';board.hidden=true;board.setAttribute('aria-label','各根主梁的荷载分担');board.innerHTML='<p>本模型的单车荷载分担 · 点一根梁继续看</p><div class="share-grid"></div>';shell.root.append(board);
const shapeInfo=document.createElement('p');shapeInfo.id='shapeInfo';shapeInfo.setAttribute('role','status');document.querySelector('.scene-hud').append(shapeInfo);
function updateDisplay(){
 const mode=$('motionMode').value,show=$('showDeformation').checked,scale=+$('deformationScale').value;
 sceneView.update(result,deformation,{revealed,selected,mode,deform:show,scale,transparent:$('transparentDeck').checked,diaphragms:$('highlightDiaphragms').checked,dimensions:$('showSpacing').checked,dimensionType:$('dimensionType').value,hideVehicle:$('hideVehicle').checked});
 board.hidden=!revealed||mode!=='total';const grid=board.querySelector('.share-grid');grid.replaceChildren();
 result.R.forEach((r,i)=>{const b=document.createElement('button');b.className='share-item'+(r< -1e-9?' negative':'');b.setAttribute('aria-pressed',String(i===selected));b.setAttribute('aria-label',`${i+1}号梁，${r.toFixed(1)}千牛，${(result.eta[i]*100).toFixed(1)}%`);b.innerHTML=`${i+1}号梁<strong>${r.toFixed(1)} kN</strong><em>${(result.eta[i]*100).toFixed(1)}%</em><i style="width:${Math.min(100,Math.abs(result.eta[i])*100)}%"></i>`;b.onclick=()=>{selected=i;updateDisplay();};grid.append(b);});
 const w=deformation.w[selected],shift=Math.abs(w)<1e-10?'不升不降':`${w<0?'上移':'下沉'} ${(Math.abs(w)*1000).toFixed(2)} mm`;
 $('sceneStatus').classList.toggle('notice',revealed&&result.negative.length>0);
 $('sceneStatus').textContent=!revealed?'':mode!=='total'?'当前只显示一个分量，切回“合在一起”看最终升降。':`${selected+1}号梁${shift}；分担 ${result.R[selected].toFixed(1)} kN。`+(result.negative.length?' 负值表示模型需要反向传力。':'');
 const explanation=mode==='settlement'?`各梁一起下沉 ${(deformation.centerSettlement*1000).toFixed(2)} mm；这里暂时拿掉转动。`:mode==='rotation'?`暂时拿掉整体下沉，只看绕刚度中心的转动。刚度中心距桥中线 ${deformation.stiffnessCenter.toFixed(2)} m。`:Math.abs(deformation.theta)<1e-14?'这一位置只有整体下沉，没有横向转动。':deformation.insideDeck?`不升不降的位置距桥中线 ${deformation.zeroX.toFixed(2)} m。和原位虚线比较，看哪一边已经上移。`:'有转动，但桥面仍全部下沉：一边下沉多，一边下沉少。';
 $('motionExplanation').textContent=explanation;shapeInfo.textContent=revealed?(show?`变形放大 ${scale} 倍 · 位移为简化模型计算值`:'当前显示未变形位置；读数保留加载后的结果'):'';
 $('sceneCaption').textContent=`教学荷载 ${state.total} kN · ${state.count}根梁 · 跨内3道横隔板`;$('offsetOut').textContent=state.carX.toFixed(2)+' m';$('offset').value=state.carX;$('bridgeSize').textContent=`B=10.80 m 为桥面全宽，L=20 m 为跨度。梁距 d=${(9.6/(state.count-1)).toFixed(2)} m；改变梁数，桥宽保持不变。`;
}
function solve(){result=distribute({...state,spacing:9.6/(state.count-1)});deformation=deformationOf(result);selected=Math.min(selected,state.count-1);updateDisplay();$('challengeFeedback').textContent='';}
function home(type='iso'){sceneView.home(type);}
function reveal(){revealed=true;$('transparentDeck').checked=true;$('mainAction').textContent='记下这个位置';$('sceneGoal').textContent='挪动车辆，和原位虚线比一比。哪根梁下沉，哪根上移？';updateDisplay();}
function keep(){if(!revealed){reveal();return;}if(trials.length>=12){$('trialMessage').textContent='本轮已记录12个方案，可先导出再刷新开始新一轮。';return;}trials.push({parameters:{...state},result:structuredClone(result),deformation:structuredClone(deformation),time:new Date().toISOString()});renderTrials();$('trialMessage').textContent=`已记下方案${trials.length}。`;$('mainAction').textContent=`已记下方案${trials.length} · 再记一次`;}
function renderTrials(){const list=$('trialList');list.replaceChildren();trials.forEach((t,i)=>{const li=document.createElement('li');li.textContent=`${i+1} · ${t.parameters.count}根梁 · 车位 ${t.parameters.carX.toFixed(2)} m · ${t.parameters.total} kN`;const b=document.createElement('button');b.textContent='恢复这个方案';b.setAttribute('aria-label','恢复方案'+(i+1));b.onclick=()=>{Object.assign(state,t.parameters);$('girderCount').value=state.count;$('totalLoad').value=state.total;$('edgeRatio').value=state.edgeRatio;solve(true);home();};li.append(document.createElement('br'),b);list.append(li);});}
function move(x){state.carX=Math.round(Math.max(-4.3,Math.min(4.3,x))*10)/10;solve();}
function challengeText(){const equal=$('challenge').value==='equal';$('challengePrompt').textContent=equal?'各梁刚度相同。调整车位，使各梁分担差异不超过平均值的1%。':'选5根梁、相同刚度；让5号梁分到至少30%，同时所有梁的分担都不为负。';$('challengeHint').textContent=equal?'先比较左右两边，向分担较少的一边挪车试试。':'先看5号梁，再留意1号梁。别只追求一个数变大。';$('challengeFeedback').textContent='';}
function check(){if(!revealed)reveal();let ok=false,message='';if(state.edgeRatio!==1)message='这项任务先保持各梁刚度相同。';else if($('challenge').value==='equal'){ok=Math.max(...result.R)-Math.min(...result.R)<=state.total/state.count*.01;message=ok?'各梁分担已经接近相同。再试试：车仍居中，只改变一根梁的刚度，会怎样？':'再比较两边梁的读数，试一个更接近中间的位置。';}else if(state.count!==5)message='这项任务指定5根梁，请先切换梁数。';else{ok=result.eta[4]>=.3-1e-10&&Math.min(...result.eta)>=-1e-10;message=ok?'达到了：5号梁不少于30%，其余梁没有负值。往外再挪，还能一直这样分吗？':'同时看5号梁的比例和其余梁的符号，再挪一点试试。';}$('challengeFeedback').textContent=message;$('challengeFeedback').dataset.passed=String(ok);return ok;}
['transparentDeck','highlightDiaphragms','showSpacing','dimensionType','hideVehicle','showDeformation','motionMode','deformationScale'].forEach(id=>$(id).onchange=updateDisplay);
$('offset').oninput=e=>move(+e.target.value);$('moveLeft').onclick=()=>move(state.carX-sceneView.screenStep());$('moveRight').onclick=()=>move(state.carX+sceneView.screenStep());$('centerCar').onclick=()=>move(0);$('girderCount').onchange=e=>{state.count=+e.target.value;solve();};$('totalLoad').onchange=e=>{state.total=+e.target.value;solve();};$('edgeRatio').onchange=e=>{state.edgeRatio=+e.target.value;solve();};
$('frontView').onclick=()=>{if(!revealed)reveal();home('section');};$('underView').onclick=()=>home('under');$('topView').onclick=()=>home('top');$('isoView').onclick=()=>home();$('mainAction').onclick=()=>revealed?keep():reveal();$('keepTrial').onclick=keep;$('challenge').onchange=challengeText;$('checkChallenge').onclick=check;
 $('exportTrials').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({schema:'bridge-transverse/v2',model:'rigid transverse connection; equivalent midspan forces on simply supported girders',units:{force:'kN',length:'m',EI:'kN*m^2',displacement:'m'},EI:3.4e6,span:20,trials},null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='各梁分担_探索记录.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('modelCode').textContent=[distribute,deformationOf,spanShape].map(fn=>fn.toString()).join('\n\n');
globalThis.TransverseBridge={get state(){return{...state}},get result(){return result},get deformation(){return deformation},get debug(){return sceneView.debug()},get trials(){return structuredClone(trials)},get revealed(){return revealed},project:(x,z=0)=>sceneView.project(x,z),check};
solve();home();challengeText();
