(()=>{'use strict';
const $=id=>document.getElementById(id),data=window.PUBLIC_BRIDGE_COURSE,svg=$('shelfSvg');
let position=.6,revealed=false,prediction=null,dragging=false;
const reactions=x=>({left:60*(1-x/1.2),right:60*x/1.2,total:60,position:x});
function setPosition(x){position=Math.min(1.1,Math.max(.1,Math.round(x*100)/100));$('bookPosition').value=position;render();}
function render(){const r=reactions(position),screenX=140+620*position/1.2;$('bookGroup').setAttribute('transform',`translate(${screenX} 0)`);$('bookGroup').setAttribute('aria-valuenow',String(position));$('bookGroup').setAttribute('aria-valuetext',`距左支承${position.toFixed(2)}米`);$('positionOutput').textContent=position.toFixed(2)+' m';$('positionLine').setAttribute('x2',screenX);$('positionTick').setAttribute('x1',screenX);$('positionTick').setAttribute('x2',screenX);$('positionLabel').textContent='距左支承 '+position.toFixed(2)+' m';$('leftForce').textContent=r.left.toFixed(1)+' N';$('rightForce').textContent=r.right.toFixed(1)+' N';$('leftArrow').setAttribute('y1',343+r.left*1.7);$('rightArrow').setAttribute('y1',343+r.right*1.7);$('reactionForces').toggleAttribute('hidden',!revealed);$('whyPanel').hidden=!revealed;$('liveResult').hidden=!revealed;$('liveResult').textContent=`左端 ${r.left.toFixed(1)} N + 右端 ${r.right.toFixed(1)} N = 60 N`;$('showForces').textContent=revealed?'收起托力，再猜一次':'看看两边各托多少';$('shelfDesc').textContent=`书重60牛，距左支承${position.toFixed(2)}米，两支承相距1.2米。${revealed?`左端托力${r.left.toFixed(1)}牛，右端托力${r.right.toFixed(1)}牛。`:''}`;if(prediction&&revealed)$('predictionFeedback').textContent=(prediction==='more'?'你选对了。':'可以再对照箭头。')+'从中间向左移，左端增加，右端减少。这个判断说的是向左移动；当前读数跟随书的实际位置。';}
$('bookPosition').addEventListener('input',e=>setPosition(+e.target.value));$('moveLeft').onclick=()=>setPosition(.3);$('moveCenter').onclick=()=>setPosition(.6);$('moveRight').onclick=()=>setPosition(.9);$('showForces').onclick=()=>{revealed=!revealed;if(!revealed){$('whyPanel').open=false;$('predictionFeedback').textContent=prediction?'已保留你的预测。挪书后再看读数。':'';}render();};
document.querySelectorAll('[data-predict]').forEach(b=>b.onclick=()=>{prediction=b.dataset.predict;document.querySelectorAll('[data-predict]').forEach(q=>q.setAttribute('aria-pressed',String(q===b)));$('predictionFeedback').textContent='已选好。可以先往左放，再看两端托力。';render();});
function fromPointer(e){const pt=svg.createSVGPoint();pt.x=e.clientX;pt.y=e.clientY;const local=pt.matrixTransform(svg.getScreenCTM().inverse());setPosition((local.x-140)/620*1.2);}
$('bookGroup').addEventListener('pointerdown',e=>{dragging=true;$('bookGroup').classList.add('dragging');$('bookGroup').setPointerCapture(e.pointerId);fromPointer(e);});$('bookGroup').addEventListener('pointermove',e=>{if(dragging)fromPointer(e);});for(const name of ['pointerup','pointercancel','lostpointercapture'])$('bookGroup').addEventListener(name,()=>{dragging=false;$('bookGroup').classList.remove('dragging');});$('bookGroup').addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();setPosition(e.key==='Home'?.1:e.key==='End'?1.1:position+(e.key==='ArrowLeft'?-.01:.01));}});
data.lessons.forEach(l=>{const o=document.createElement('option');o.value=l.id;o.textContent=String(l.id).padStart(2,'0')+' · '+l.title;$('lessonSelect').append(o);});
function choose(id){const l=data.lessons.find(l=>l.id===Number(id))||data.lessons[0];$('lessonSelect').value=l.id;$('lessonOne').hidden=l.id!==1;$('otherLesson').hidden=l.id===1;if(l.id!==1){$('otherStatus').textContent=`第 ${l.id} 讲 · ${l.status}`;$('otherTitle').textContent=l.title;$('otherEveryday').textContent=l.everyday;$('otherGain').textContent=l.gain;$('otherBridge').textContent=l.bridge;$('otherAction').textContent=l.action;$('otherLab').href=l.href;$('otherAssetStatus').textContent=l.assetStatus;$('otherTransfer').textContent=l.transfer;}try{history.replaceState(null,'','#lesson-'+l.id);}catch{} }
$('lessonSelect').onchange=e=>choose(e.target.value);$('backSample').onclick=()=>{choose(1);$('lessonSelect').focus();scrollTo({top:0,behavior:'auto'});};
data.script.split(/\n\s*\n/).forEach(text=>{const p=document.createElement('p');p.textContent=text;$('scriptText').append(p);});
function feedback(id,ok,text){const el=$(id);el.dataset.correct=String(ok);el.textContent=text;}
document.querySelectorAll('[name=q1]').forEach(q=>q.onchange=()=>feedback('feedback1',q.value==='a',q.value==='a'?'对。总力不变，位置改变后还要重新满足转动平衡。':'再想一步：两端之和要等于60 N，书的位置还影响转动作用。可以回到书架再挪一次。'));
$('checkQ2').onclick=()=>{const raw=$('q2').value,v=Number(raw);if(!raw||!Number.isFinite(v)){feedback('feedback2',false,'先填入你看到的5号梁读数，单位是kN。');return;}const ok=Math.abs(v-36)<=.2;feedback('feedback2',ok,ok?'对，120 kN 的30%是36 kN。当前模型中，向5号梁一侧偏约1.20 m可得到这一分担；还要核对各梁总和。':'再核对：总力是120 kN，5号梁承担其中30%。请保持五根梁刚度相同，并对照桥上的读数。');};
document.querySelectorAll('[name=q3]').forEach(q=>q.onchange=()=>feedback('feedback3',q.value==='no',q.value==='no'?'对。荷载居中，但刚度已经不对称。多根梁还要满足共同变形，不能只凭居中就平均分。':'车的位置只是一项条件。试着保持车居中，在桥的“换几根梁”中改变5号梁刚度，再比较分担。'));
globalThis.PublicBridgeCourse={get result(){return reactions(position);},get revealed(){return revealed;},get lessonCount(){return data.lessons.length;},setPosition};render();choose(Number(location.hash.match(/lesson-(\d+)/)?.[1]||1));
})();
