(()=>{'use strict';const $=id=>document.getElementById(id),fmt=x=>Number(x.toPrecision(4));let tab='eccentric',value=.1;
const line=(x,y,xx,yy,c='#718697')=>`<line x1="${x}" y1="${y}" x2="${xx}" y2="${yy}" stroke="${c}" stroke-width="2"/>`,text=(x,y,s,c='#17324d')=>`<text x="${x}" y="${y}" text-anchor="middle" fill="${c}" font-size="17">${s}</text>`,path=(pts,c='#176ea0')=>`<polyline points="${pts.map(p=>p.join(',')).join(' ')}" fill="none" stroke="${c}" stroke-width="4"/>`,svg=s=>`<svg viewBox="0 0 520 310" role="img">${s}</svg>`;
const data={eccentric:{title:'平均项 + 偏心修正：连续应力与离散反力',lead:'两幅图共用偏心比 e/B。左边把压力分布在连续矩形截面，右边分给四个等刚度支承；共同要求是合力与合矩守恒。',label:'偏心比 e/B',min:0,max:.3,step:.005,start:.1,boundary:'相同的“平均＋线性梯度”思路不意味着相同阈值。连续矩形截面的核心边界是 1/6；本页四支承布置最小反力为零的偏心比是 5/24。负压力或负反力出现后，仅受压接触模型需重新求解。',question:'e/B=0.18 时，连续矩形的一侧已出现拉应力，四支承却仍全部为正。为什么不矛盾？',explanation:'二者使用同样的平衡与线性分布形式，但力分布的积分域不同：连续截面依赖面积二次矩，离散支承依赖 Σyᵢ²。本页四个支承位于 B 的 ±1/8、±3/8，不能把连续截面 h/6 阈值直接搬过去。开裂、脱空和RC破坏类型又是不同层次的问题。'},form:{title:'形状服从平衡：同样的抛物线，不同的拉压后果',lead:'固定跨度 L=1、水平投影均布荷载 q=1，把矢高/垂度同步改变。拱与索共享 H=qL²/(8f)，但压杆稳定与索的张紧条件并不相同。',label:'矢跨比 / 垂跨比 f/L',min:.05,max:.3,step:.005,start:.15,boundary:'这里比较同一水平投影均布荷载下的三铰合理拱与理想柔索。它不是沿索长自重的精确悬链线，也没有计算拱的屈曲或柔索的几何刚度。换成半跨活载，原合理拱轴一般产生弯矩。',question:'把同一平衡形状由受拉反转成受压以后，为什么不能据此直接复制承载能力？',explanation:'平衡方程相似只保留合力传递。受压体系还受整体与局部稳定、初始缺陷、支座位移和弯矩影响；柔索则要求张紧并按当前荷载重新找形。轴力符号改变，使可接受的工作状态与失效机制不同。'},scale:{title:'先声明什么不变，再谈尺度指数',lead:'全尺寸几何相似放大，E 与密度不变。下面四行同时使用同一个 λ，只改变加载规则，比较应力 σ/σ₀ 与挠度 δ/δ₀。',label:'长度比例 λ',min:.5,max:3,step:.05,start:2,boundary:'各行都是单独的假设情景，不能混为同一荷载组合。尺寸的二次、三次或四次幂不等于材料或荷载响应非线性；这些结果仍可来自线弹性梁。仅增加跨度而保持截面不变，又是另一种尺度试验。',question:'λ=2 时，固定集中力下挠度减半，自重下挠度却增至四倍。哪项变化使结论反向？',explanation:'全尺寸相似梁有 I∝λ⁴、L∝λ。固定 P 时 δ∝PL³/(EI)∝λ⁻¹；自重线荷载 q∝A∝λ²，δ∝qL⁴/(EI)∝λ²。两者加载规则不同，因此结果并不矛盾。'}};
function render(){const d=data[tab];$('number').value=fmt(value);$('parameter').value=value;let html='',code='';
if(tab==='eccentric'){const e=value,ys=[-.375,-.125,.125,.375],sum=ys.reduce((s,y)=>s+y*y,0),R=ys.map(y=>.25+e*y/sum),min=1-6*e,max=1+6*e;let a=line(180,50,180,250)+line(65,150,445,150);for(let i=0;i<=20;i++){let t=i/20,y=250-200*t,q=1+12*e*(t-.5);a+=line(180,y,180+q*80,y,q>=0?'#176ea0':'#be661b');}a+=path([[180,50],[180+max*80,50],[180+min*80,250],[180,250]])+text(90,43,'y=+B/2')+text(90,272,'y=−B/2')+text(330,288,'σ / (N/A)');let b=line(55,180,465,180);R.forEach((r,i)=>{let x=85+i*115,h=r*140;b+=`<rect x="${x-20}" y="${r>=0?180-h:180}" width="40" height="${Math.abs(h)}" fill="${r>=0?'#176ea0':'#be661b'}"/>`+text(x,225,fmt(ys[i]))+text(x,260,fmt(r));});b+=text(260,28,'四支承位置 y/B 与分配系数')+text(260,300,'蓝：正；橙：负');html=`<div class="pair"><article><h3>材料力学：矩形偏心受压</h3>${svg(a)}<p class="metric">最小归一压应力 ${fmt(min)}</p><p>σ/(N/A)=1+12(e/B)(y/B)</p><p>边缘变号阈值：e/B=1/6≈0.1667</p></article><article><h3>桥梁工程：四梁横向分配</h3>${svg(b)}<p class="metric">最小分配系数 ${fmt(Math.min(...R))}</p><p>ηᵢ=1/4+(e/B)(yᵢ/B)/Σ(yⱼ/B)²</p><p>合力 ${fmt(R.reduce((s,r)=>s+r,0))}；合矩 ${fmt(R.reduce((s,r,i)=>s+r*ys[i],0))}；阈值 5/24≈0.2083</p></article></div>`;code=`const e = ${fmt(e)}; // e/B\nconst sigmaMin = 1 - 6*e;\nconst y = [-3/8, -1/8, 1/8, 3/8];\nconst sumY2 = y.reduce((s,t) => s+t*t, 0);\nconst eta = y.map(t => 1/4 + e*t/sumY2);`;
}else if(tab==='form'){const f=value,H=1/(8*f);function shape(sign){let s=line(50,160,470,160);s+=path(Array.from({length:61},(_,i)=>{let x=i/60;return[50+420*x,160+sign*400*f*4*x*(1-x)]}));for(let x=80;x<470;x+=45)s+=line(x,30,x,58,'#be661b')+path([[x-4,52],[x,58],[x+4,52]],'#be661b');s+=text(260,290,sign<0?'压力传向拱脚；须检查稳定':'张力传向锚碇；须保持张紧');return svg(s);}html=`<div class="pair"><article><h3>三铰合理拱：受压</h3>${shape(-1)}<p class="metric">水平推力 H=${fmt(H)}</p><p>y=4f x(1−x)，M=M₀−Hy=0</p></article><article><h3>理想柔索：受拉</h3>${shape(1)}<p class="metric">水平分力 H=${fmt(H)}</p><p>垂度曲线 4f x(1−x)，只对应给定荷载</p></article></div>`;code=`const L=1, q=1, f=${fmt(f)};\nconst H=q*L*L/(8*f);\nconst y=x => 4*f*(x/L)*(1-x/L);\nconst M0=x => q*x*(L-x)/2;\nconst archMoment=x => M0(x)-H*y(x); // 本荷载下为0`;
}else{const l=value,rows=[['集中力 P 固定',-2,-1],['线荷载 q 固定',-1,0],['面压力 p 固定，宽度同比放大',0,1],['自重：q=ρgA 随面积增长',1,2]];html='<table><thead><tr><th>保持不变的条件</th><th>应力 σ/σ₀</th><th>挠度 δ/δ₀</th></tr></thead><tbody>'+rows.map(([s,a,b])=>`<tr><td>${s}</td><td>λ^${a} = <strong>${fmt(l**a)}</strong></td><td>λ^${b} = <strong>${fmt(l**b)}</strong></td></tr>`).join('')+'</tbody></table><div class="pair"><article><h3>荷载总量如何变化？</h3><p>固定 P：不变；固定 q：λ；固定面压力：λ²；自重：λ³。</p></article><article><h3>结构自身如何变化？</h3><p>A：λ²；I：λ⁴；W：λ³；横向位移刚度 EI/L³：λ。</p></article></div>';code=`const lambda=${fmt(l)};\n// 每行：[应力指数, 挠度指数]\nconst exponents=[[-2,-1],[-1,0],[0,1],[1,2]];\nconst responses=exponents.map(([s,d]) =>\n  ({stress:lambda**s, deflection:lambda**d}));`;
}$('stage').innerHTML=html;$('code').textContent=code;}
function select(t){tab=t;const d=data[t];value=d.start;document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-selected',b.dataset.tab===t));$('topic').textContent=d.title;$('lead').textContent=d.lead;$('parameter-label').textContent=d.label;for(const el of [$('parameter'),$('number')])Object.assign(el,{min:d.min,max:d.max,step:d.step});$('boundary').textContent=d.boundary;$('question').textContent=d.question;$('explanation').textContent=d.explanation;$('answer').value='';$('saved').textContent='';document.querySelector('details').open=false;render();}
function change(v){if(Number.isFinite(v)){value=Math.max(data[tab].min,Math.min(data[tab].max,v));render();}}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>select(b.dataset.tab));$('parameter').oninput=e=>change(+e.target.value);$('number').onchange=e=>change(+e.target.value);$('reset').onclick=()=>change(data[tab].start);$('save-answer').onclick=()=>{const record={schema:'bridge-analogy/v1',tab,parameter:value,answer:$('answer').value,assumptions:data[tab].boundary,time:new Date().toISOString()},url=URL.createObjectURL(new Blob([JSON.stringify(record,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='跨课程类比-'+tab+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('saved').textContent='已导出判断与当前参数；开放解释题没有自动判分。';};window.AnalogyLab={select,change,get state(){return{tab,value}}};select(tab);
})();
