import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
const $=id=>document.getElementById(id),MODEL='../../assets/publication/blender-bridge/models/highway_t_girder.glb?v=rebar-20260907';
const TYPES={upper:{name:'上部架立纵筋',color:'#b95d22'},lower:{name:'下部普通纵筋',color:'#913856'},web:{name:'腹板构造纵筋',color:'#7c6638'},flange:{name:'翼缘分布纵筋',color:'#866090'},stirrups:{name:'腹板闭合箍筋',color:'#267b70'},ties:{name:'翼缘闭合联系筋',color:'#479055'},ducts:{name:'预应力孔道',color:'#326db4'}};
const EXTRAS={upper_erection:'upper',lower_longitudinal:'lower',web_longitudinal:'web',flange_longitudinal:'flange',main_stirrup:'stirrups',flange_tie:'ties',prestress_duct:'ducts'};
const PRESETS={segment:{title:'看一段',note:'只看中间 3 m，看看纵筋和箍筋怎样放在一起。',range:[42,45],direction:[1,.48,1.4]},whole:{title:'整片梁',note:'沿着整片梁看纵筋与孔道；需要看清箍筋时，回到“看一段”。',range:null,direction:[.75,.55,1.3]},section:{title:'横断面',note:'沿梁轴看一小段，把主箍、上部架立筋和翼缘联系筋看清。',range:[44.72,44.78],direction:[1,.0001,.0001]}};
const enabled=Object.fromEntries(Object.keys(TYPES).map(key=>[key,true])),stage=$('stage'),canvas=$('canvas');
let renderer,scene,camera,controls,root,concrete,capGroup,selected,current='segment',pending=false,last=0,loading=false,loadPromise,startPointer,activeType='upper';
const parts=[],allNames=[],originalPositions=new Map(),labels=new Map(),anchorCache=new Map(),raycaster=new THREE.Raycaster();
let clipPlanes=[],rangeBox=new THREE.Box3();
function category(name,extras={}){if(EXTRAS[extras.rebar_group])return EXTRAS[extras.rebar_group];const match=name.match(/^Rebar_Longitudinal(\d+)$/);if(match){const index=Number(match[1]);return index<=4?'lower':index<=8?'web':index===11||index===14?'upper':'flange';}if(name.startsWith('Rebar_Stirrup'))return 'stirrups';if(name.startsWith('Rebar_FlangeTie'))return 'ties';if(name.startsWith('Prestress_Duct'))return 'ducts';return null;}
function nameOf(mesh){return mesh.userData.component_id||mesh.name;}
function init(){
 if(renderer)return;renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1;renderer.localClippingEnabled=true;
 scene=new THREE.Scene();scene.background=new THREE.Color('#edf3f6');camera=new THREE.PerspectiveCamera(39,1,.002,1000);scene.add(new THREE.HemisphereLight(0xffffff,0x889baa,1.35));
 for(const [position,intensity] of [[[30,70,50],2],[[55,0,-20],1]]){const light=new THREE.DirectionalLight(0xffffff,intensity);light.position.set(...position);scene.add(light);}
 controls=new OrbitControls(camera,canvas);controls.enableDamping=!matchMedia('(prefers-reduced-motion: reduce)').matches;controls.dampingFactor=.14;controls.minDistance=.3;controls.maxDistance=120;controls.addEventListener('change',requestRender);new ResizeObserver(resize).observe(stage);resize();
 canvas.addEventListener('pointerdown',event=>startPointer={x:event.clientX,y:event.clientY,button:event.button});canvas.addEventListener('pointerup',event=>{if(startPointer?.button===0&&Math.hypot(event.clientX-startPointer.x,event.clientY-startPointer.y)<5)pick(event.clientX,event.clientY);});canvas.addEventListener('contextmenu',event=>event.preventDefault());document.addEventListener('visibilitychange',()=>{if(!document.hidden)requestRender();});
}
function resize(){if(!renderer)return;const direction=controls?camera.position.clone().sub(controls.target):null;renderer.setSize(stage.clientWidth,stage.clientHeight,false);camera.aspect=stage.clientWidth/Math.max(1,stage.clientHeight);camera.updateProjectionMatrix();if(root&&direction?.lengthSq())frame(rangeBox,direction);else requestRender();}
function requestRender(){if(!renderer||pending||document.hidden)return;pending=true;requestAnimationFrame(draw);}
function draw(time){pending=false;controls.update(Math.min((time-last)/1000,.05));last=time;renderer.render(scene,camera);updateLabels();}
function frame(box,direction){if(box.isEmpty())return;const center=box.getCenter(new THREE.Vector3()),dir=direction.clone().normalize(),right=new THREE.Vector3().crossVectors(camera.up,dir).normalize(),up=new THREE.Vector3().crossVectors(dir,right).normalize(),v=Math.tan(THREE.MathUtils.degToRad(camera.fov)/2),h=v*camera.aspect;let distance=1;
 for(const x of [box.min.x,box.max.x])for(const y of [box.min.y,box.max.y])for(const z of [box.min.z,box.max.z]){const point=new THREE.Vector3(x,y,z).sub(center),depth=point.dot(dir);distance=Math.max(distance,depth+Math.abs(point.dot(right))/h*1.38,depth+Math.abs(point.dot(up))/v*1.45);}
 const damping=controls.enableDamping;controls.enableDamping=false;controls.update();controls.target.copy(center);camera.position.copy(center).addScaledVector(dir,distance);camera.near=.002;camera.updateProjectionMatrix();controls.update();controls.enableDamping=damping;requestRender();}
function clearSelected(){if(selected){selected.material.emissive?.set('#000000');selected=null;}$('detail').textContent='单击钢筋或孔道，查看名称。';$('focus').disabled=true;}
function updateVisibility(){if(!root)return;for(const mesh of parts)mesh.visible=enabled[mesh.userData.rebarType];concrete.visible=$('concrete').checked&&current!=='section';if(capGroup)for(const mesh of capGroup.children)mesh.visible=mesh.userData.isConcrete?$('concrete').checked:enabled[mesh.userData.rebarType];if(selected&&!selected.visible)clearSelected();requestRender();}
function boundsFor(mesh){const box=new THREE.Box3().setFromObject(mesh);const range=PRESETS[current].range;if(range){box.min.x=Math.max(box.min.x,range[0]);box.max.x=Math.min(box.max.x,range[1]);}return box;}
function setPreset(key){if(!PRESETS[key])throw new Error('Unknown preset');current=key;$('view-title').textContent=PRESETS[key].title;$('view-note').textContent=PRESETS[key].note;document.querySelectorAll('[data-preset]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.preset===key)));if(!root)return;clearSelected();
 const range=PRESETS[key].range;clipPlanes=range?[new THREE.Plane(new THREE.Vector3(1,0,0),-range[0]),new THREE.Plane(new THREE.Vector3(-1,0,0),range[1])]:[];for(const mesh of [...parts,concrete]){mesh.material.clippingPlanes=clipPlanes;mesh.material.needsUpdate=true;}
 rangeBox=boundsFor(concrete);anchorCache.clear();makeSectionCaps();updateVisibility();frame(rangeBox,new THREE.Vector3(...PRESETS[key].direction));
}
function createLegend(){for(const [key,type] of Object.entries(TYPES)){const row=document.createElement('div');row.className='legend-row';row.style.setProperty('--kind',type.color);const input=document.createElement('input');input.type='checkbox';input.checked=true;input.disabled=true;input.id='show-'+key;input.onchange=()=>{enabled[key]=input.checked;updateVisibility();};const label=document.createElement('label');label.htmlFor=input.id;const swatch=document.createElement('span');swatch.className='swatch';label.append(swatch,document.createTextNode(type.name));const button=document.createElement('button');button.textContent='靠近';button.disabled=true;button.setAttribute('aria-label','靠近'+type.name);button.onclick=()=>focusType(key);row.append(input,label,button);$('legend').append(row);
 const element=document.createElement('span');element.className='scene-label';element.textContent=type.name;element.style.setProperty('--kind',type.color);element.hidden=true;$('labels').append(element);const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('stroke',type.color);const point=document.createElementNS('http://www.w3.org/2000/svg','circle');point.setAttribute('r','3');point.setAttribute('fill',type.color);$('leaders').append(line,point);labels.set(key,{element,line,point});}}
function labelAnchor(key){if(anchorCache.has(key))return anchorCache.get(key)?.clone()||null;const candidates=parts.filter(mesh=>mesh.userData.rebarType===key),visible=candidates.filter(mesh=>!boundsFor(mesh).isEmpty());if(!visible.length)return null;let mesh;
 if(key==='upper')mesh=visible.find(mesh=>nameOf(mesh)==='Rebar_Longitudinal11')||visible[0];else if(key==='lower')mesh=visible.find(mesh=>nameOf(mesh)==='Rebar_Longitudinal0')||visible[0];else if(key==='ducts')mesh=visible.find(mesh=>nameOf(mesh)==='Prestress_Duct2')||visible[0];else mesh=visible[Math.floor(visible.length/2)];
 const box=boundsFor(mesh),center=box.getCenter(new THREE.Vector3());if(key==='stirrups'||key==='ties'){center.y=box.max.y;center.z=box.getCenter(new THREE.Vector3()).z;}else{const outline=sectionOutline(mesh,center.x);if(outline.length)center.copy(outline.reduce((sum,p)=>sum.add(p),new THREE.Vector3()).multiplyScalar(1/outline.length));}anchorCache.set(key,center.clone());return center;}
function updateLabels(){if(!root)return;const width=stage.clientWidth,height=stage.clientHeight,mobile=width<600;const requested=new Set(activeType==='upper'||activeType==='stirrups'||activeType==='ducts'?['upper','stirrups','ducts']:[activeType,'stirrups','ducts']);
 for(const [key,item] of labels){const anchor=labelAnchor(key),show=enabled[key]&&anchor!==null&&requested.has(key);item.element.hidden=!show;item.line.style.display=show?'':'none';item.point.style.display=show?'':'none';if(!show)continue;const projected=anchor.project(camera);if(Math.abs(projected.z)>1||Math.abs(projected.x)>1.05||Math.abs(projected.y)>1.05){item.element.hidden=true;item.line.style.display='none';item.point.style.display='none';continue;}const right=key==='stirrups'||key==='ducts',bottom=key==='ducts';const x=right?width-(mobile?112:160):(mobile?10:20),y=bottom?height-(mobile?72:95):(mobile?54:65);item.element.style.left=x+'px';item.element.style.top=y+'px';const px=(projected.x+1)*width/2,py=(1-projected.y)*height/2;const labelWidth=item.element.offsetWidth,labelHeight=item.element.offsetHeight;item.line.setAttribute('x1',x+labelWidth/2);item.line.setAttribute('y1',y+labelHeight/2);item.line.setAttribute('x2',px);item.line.setAttribute('y2',py);item.point.setAttribute('cx',px);item.point.setAttribute('cy',py);}}
function focusType(key){const box=new THREE.Box3();for(const mesh of parts)if(mesh.userData.rebarType===key)box.union(boundsFor(mesh));if(box.isEmpty())return;activeType=key;enabled[key]=true;$('show-'+key).checked=true;updateVisibility();frame(box,camera.position.clone().sub(controls.target));$('detail').textContent=TYPES[key].name;}
function pick(x,y){if(!root)return;const rect=canvas.getBoundingClientRect();raycaster.setFromCamera(new THREE.Vector2((x-rect.left)/rect.width*2-1,-(y-rect.top)/rect.height*2+1),camera);raycaster.params.Line.threshold=.006;const targets=[...parts,...(capGroup?.children||[])].filter(mesh=>mesh.visible&&!mesh.userData.isConcrete);const hits=raycaster.intersectObjects(targets,false),range=PRESETS[current].range;const hit=hits.find(hit=>hit.object.userData.sourceName||!range||(hit.point.x>=range[0]&&hit.point.x<=range[1]));clearSelected();if(hit){selected=hit.object.userData.sourceName?parts.find(mesh=>nameOf(mesh)===hit.object.userData.sourceName):hit.object;selected.material.emissive.set('#6b4717');selected.material.emissiveIntensity=.38;const key=selected.userData.rebarType;activeType=key;$('detail').textContent=TYPES[key].name+(key==='ducts'?'\n这里表示预留孔道，不是钢绞线。':'');$('focus').disabled=false;}requestRender();}
// Derive a thin section display cap from the source mesh/plane intersections.
// Ordinary bars have filled sections; ducts remain outline-only, without invented strands.
function sectionOutline(mesh,x){const geometry=mesh.geometry,positions=geometry.getAttribute('position'),index=geometry.index,points=new Map();mesh.updateWorldMatrix(true,false);const read=i=>new THREE.Vector3().fromBufferAttribute(positions,index?index.getX(i):i).applyMatrix4(mesh.matrixWorld),add=p=>points.set(p.y.toFixed(5)+','+p.z.toFixed(5),p);
 const count=index?index.count:positions.count;for(let i=0;i<count;i+=3){const vertices=[read(i),read(i+1),read(i+2)];for(let k=0;k<3;k++){const a=vertices[k],b=vertices[(k+1)%3];if((a.x-x)*(b.x-x)<0)add(a.clone().lerp(b,(x-a.x)/(b.x-a.x)));}}
 const array=[...points.values()];if(array.length<3)return [];const center=array.reduce((sum,p)=>sum.add(p),new THREE.Vector3()).multiplyScalar(1/array.length);array.sort((a,b)=>Math.atan2(a.z-center.z,a.y-center.y)-Math.atan2(b.z-center.z,b.y-center.y));return array;}
function concreteSectionLine(x){const geometry=concrete.geometry,positions=geometry.getAttribute('position'),index=geometry.index,points=[];const read=i=>new THREE.Vector3().fromBufferAttribute(positions,index?index.getX(i):i).applyMatrix4(concrete.matrixWorld);for(let i=0;i<(index?index.count:positions.count);i+=3){const vertices=[read(i),read(i+1),read(i+2)],hits=[];for(let k=0;k<3;k++){const a=vertices[k],b=vertices[(k+1)%3];if((a.x-x)*(b.x-x)<0){const point=a.clone().lerp(b,(x-a.x)/(b.x-a.x));point.x=x+.0003;hits.push(point);}}if(hits.length===2)points.push(...hits);}const line=new THREE.LineSegments(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color:'#b6c4cb',transparent:true,opacity:.75}));line.userData.isConcrete=true;return line;}
function makeSectionCaps(){if(capGroup){scene.remove(capGroup);capGroup.traverse(object=>{object.geometry?.dispose();object.material?.dispose();});}capGroup=new THREE.Group();scene.add(capGroup);if(current!=='section')return;
 const x=PRESETS.section.range[1];for(const mesh of parts){const key=mesh.userData.rebarType;if(key==='stirrups'||key==='ties')continue;const outline=sectionOutline(mesh,x);if(outline.length<3)continue;for(const point of outline)point.x=x+.0002;let cap;
 if(key==='ducts'){cap=new THREE.LineLoop(new THREE.BufferGeometry().setFromPoints(outline),new THREE.LineBasicMaterial({color:TYPES[key].color}));}else{const center=outline.reduce((sum,p)=>sum.add(p),new THREE.Vector3()).multiplyScalar(1/outline.length),vertices=[];for(let i=0;i<outline.length;i++){vertices.push(...center.toArray(),...outline[i].toArray(),...outline[(i+1)%outline.length].toArray());}const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));cap=new THREE.Mesh(geometry,new THREE.MeshBasicMaterial({color:TYPES[key].color,side:THREE.DoubleSide}));}cap.userData.rebarType=key;cap.userData.sourceName=nameOf(mesh);capGroup.add(cap);}capGroup.add(concreteSectionLine(x));}
async function load(){if(root)return true;if(loadPromise)return loadPromise;loading=true;$('load').disabled=true;$('load').textContent='正在载入…';loadPromise=(async()=>{try{init();const gltf=await new GLTFLoader().loadAsync(MODEL,event=>{if(event.total)$('status').textContent=`读取模型 ${Math.round(event.loaded/event.total*100)}%`;});root=gltf.scene;root.traverse(object=>{if(!object.isMesh)return;const name=nameOf(object);allNames.push(name);object.visible=false;originalPositions.set(object.uuid,object.position.clone());const key=category(name,object.userData);if(key){object.userData.rebarType=key;object.material=new THREE.MeshStandardMaterial({color:TYPES[key].color,metalness:.1,roughness:.56,side:THREE.DoubleSide});parts.push(object);}else if(name==='C1_S2_Girder1'){concrete=object;object.material=new THREE.MeshStandardMaterial({color:'#bdcbd0',transparent:true,opacity:.12,depthWrite:false,roughness:.9,side:THREE.DoubleSide});}});if(!concrete||!Object.keys(TYPES).every(key=>parts.some(mesh=>mesh.userData.rebarType===key)))throw new Error('配筋构件不齐，请核对模型版本');scene.add(root);root.updateMatrixWorld(true);for(const element of document.querySelectorAll('#legend input,#legend button,#concrete,#save,#reset'))element.disabled=false;$('cover').classList.add('hidden');$('status').textContent='单独观察一片梁';setPreset(current);return true;}catch(error){console.error(error);if(root)scene?.remove(root);root=null;parts.length=0;allNames.length=0;originalPositions.clear();$('load').disabled=false;$('load').textContent='重试载入';$('status').textContent='载入失败，请用教材网站或本地网页服务打开';return false;}finally{loading=false;loadPromise=null;}})();return loadPromise;}
async function savePNG(){if(!root)return;$('save').disabled=true;try{renderer.render(scene,camera);updateLabels();const output=document.createElement('canvas');output.width=canvas.width;output.height=canvas.height;const ctx=output.getContext('2d');ctx.drawImage(canvas,0,0);const scale=canvas.width/stage.clientWidth;ctx.scale(scale,scale);ctx.font=`${stage.clientWidth<600?9:11}px "Microsoft YaHei",sans-serif`;ctx.textBaseline='top';for(const [key,item] of labels){if(item.element.hidden)continue;const x=parseFloat(item.element.style.left),y=parseFloat(item.element.style.top),w=item.element.offsetWidth,h=item.element.offsetHeight;ctx.strokeStyle=TYPES[key].color;ctx.lineWidth=1.25;ctx.beginPath();ctx.moveTo(Number(item.line.getAttribute('x1')),Number(item.line.getAttribute('y1')));ctx.lineTo(Number(item.line.getAttribute('x2')),Number(item.line.getAttribute('y2')));ctx.stroke();ctx.fillStyle='#ffffff';ctx.fillRect(x,y,w,h);ctx.strokeRect(x,y,w,h);ctx.fillStyle=TYPES[key].color;ctx.fillText(TYPES[key].name,x+5,y+4);}const blob=await new Promise((resolve,reject)=>output.toBlob(value=>value?resolve(value):reject(new Error('PNG export failed')),'image/png'));const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`bridge-rebar-${current}.png`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('status').textContent='已保存带名称的当前视角';}catch(error){console.error(error);$('status').textContent='保存失败，请重试';}finally{$('save').disabled=false;}}
createLegend();$('load').onclick=load;$('save').onclick=savePNG;$('concrete').onchange=updateVisibility;document.querySelectorAll('[data-preset]').forEach(button=>button.onclick=()=>setPreset(button.dataset.preset));$('reset').onclick=()=>{activeType='upper';for(const key of Object.keys(TYPES)){enabled[key]=true;$('show-'+key).checked=true;}$('concrete').checked=true;setPreset('segment');};$('focus').onclick=()=>{if(selected)frame(boundsFor(selected),camera.position.clone().sub(controls.target));};
window.bridgeRebar=Object.freeze({load,setPreset,snapshot:()=>({loaded:!!root,loading,preset:current,range:PRESETS[current].range,partCount:parts.length,visiblePartCount:parts.filter(mesh=>mesh.visible&&!boundsFor(mesh).isEmpty()).length,enabledTypes:{...enabled},counts:Object.fromEntries(Object.keys(TYPES).map(key=>[key,parts.filter(mesh=>mesh.userData.rebarType===key).length])),inSlice:Object.fromEntries(Object.keys(TYPES).map(key=>[key,parts.filter(mesh=>mesh.userData.rebarType===key&&!boundsFor(mesh).isEmpty()).length])),visibleLabels:[...labels].filter(([,item])=>!item.element.hidden).map(([key])=>TYPES[key].name),meshPositionsIntact:parts.every(mesh=>mesh.position.equals(originalPositions.get(mesh.uuid))),concreteVisible:concrete?.visible,capCount:capGroup?.children.length||0,selected:selected?nameOf(selected):null})});
